# Generated by Django 5.1.6 on 2025-02-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECSMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_field', models.CharField(max_length=255, unique=True)),
                ('ecs_field', models.CharField(max_length=255)),
                ('embedding', models.BinaryField()),
            ],
        ),
    ]
