# Generated by Django 5.1.6 on 2025-03-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECSMappingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_field', models.CharField(max_length=255)),
                ('ecs_field', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ecsmapping',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ecsmapping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecsmapping',
            name='example_log_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
